export {
  useQueryPolls,
  useQueryPollDetail,
  useQueryPollScores,
  useQueryPublicPoll,
  useMutationCreatePoll,
  useMutationUpdatePoll,
  useMutationDeletePoll,
  useMutationRestorePoll,
  useMutationCreateSlide,
  useMutationUpdateSlide,
  useMutationDeleteSlide,
  useMutationReorderSlides,
  useMutationSubmitVote,
  useQuerySlideResults,
  useMutationUploadImage,
} from './queries'
