export const QUERY_KEYS = {
  EVENTS: 'events',
  EVENT_DETAIL: 'event-detail',
  EVENT_QUESTIONS: 'event-questions',
  SECTIONS: 'sections',
  RESPONSES: 'responses',
  RESPONSE_PROGRESS: 'response-progress',
  ANALYTICS_EVENTS: 'analytics-events',
  PUBLIC_EVENT: 'public-event',
  POLLS: 'polls',
  POLL_DETAIL: 'poll-detail',
  POLL_SCORES: 'poll-scores',
  PUBLIC_POLL: 'public-poll',
  EMAIL_BLASTS: 'email-blasts',
  EMAIL_BLAST_DETAIL: 'email-blast-detail',
  EMAIL_BLAST_DRAFT: 'email-blast-draft',
  SUBMIT_FORM_SETTINGS: 'submit-form-settings',
  PERMISSION_REQUESTS: 'permission-requests',
  EVENT_AUDIT_LOGS: 'event-audit-logs',
} as const
